Add CHT example
ansys/pyfluent-examples pull request #76
Opened 2023-09-27 10:46 UTC by hpohekar

2023-09-28 16:36 UTC, hpohekar commented
@seanpearsonuk @mkundu1

2023-09-29 07:31 UTC, prmukherj approved these changes

2023-09-29 08:13 UTC, abhishekchitwar requested changes
@hpohekar , @PySRG 

Please add thumbnail to this example. It would be great if you could update to add the description on thumbnail (instead) objective on hover. Please refer to Ahmed body / Ablation examples.

Thanks!

2023-09-29 09:36 UTC, abhishekchitwar approved these changes
Thanks!

2023-09-29 09:36 UTC, merged